services:
  db:
    image: postgres:15.4-alpine3.18
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogapp_db
    ports:
      - "5435:5432"
    networks:
      - blogapp-network
  blogapp:
    image: blogapp
    restart: always
    build:
      context: .
      dockerfile: blogapi/Dockerfile
    working_dir: /3Wings-challenge/blogapi
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      DB_DEV_URL: ${DB_DEV_URL}
      DB_DEV_USER: ${DB_DEV_USER}
      DB_DEV_PASSWORD: ${DB_DEV_PASSWORD}
    ports:
      - "8085:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - blogapp-network
networks:
  blogapp-network:
    driver: bridge